version: 1.0.{build}
branches:
  only:
  - master
before_build:
- cmd: nuget restore SchoolSystem/SchoolSystem.sln
build:
  project: SchoolSystem/SchoolSystem.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal