//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem.WebForms {
    
    
    public partial class _Default {
        
        /// <summary>
        /// StudentScheduleControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SchoolSystem.WebForms.CustomControls.Home.StudentScheduleControl StudentScheduleControl;
        
        /// <summary>
        /// updatePanelImportant control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel updatePanelImportant;
        
        /// <summary>
        /// NewsfeedControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SchoolSystem.WebForms.CustomControls.Home.NewsfeedControl NewsfeedControl;
    }
}
