//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem.WebForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newsfeeds
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsImportant { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
